<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert(
            [
                [
                    'sku' => 'P0001',
                    'barcode' => null,
                    'extension' => 'jpg',
                    'name_en' => 'Sanita My Home Floor Detergent',
                    'name_ar' => 'منظف أرضيات سانيتا ماي هوم',
                    'name_ku' => 'کۆڕکردنی زەویی سانیتا مەڵەکەم',
                    'small_description_en' => 'Powerful floor cleaner for all surfaces',
                    'small_description_ar' => 'منظف قوي لجميع أنواع الأرضيات',
                    'small_description_ku' => 'پاککارییەکی بەهێز بۆ هەموو جۆری زەوی',
                    'unit_price' => 3.50,
                    'shelf_price' => 4.00,
                    'old_price' => 4.50,
                    'available_quantity' => 100,
                    'threshold' => 5,
                    'product_line_code' => 'CLN01',
                    'product_line_description' => 'Cleaning Solutions',
                    'family_code' => 'FLOOR',
                    'family_description' => 'Floor Care',
                    'subcategories_id' => 2,
                    'brands_id' => 1,
                    'tax_id' => 1,
                    'hidden' => 0,
                    'automatic_hide' => 0,
                    'cancelled' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'sku' => 'P0002',
                    'barcode' => null,
                    'extension' => 'png',
                    'name_en' => 'Sanita My Home Glass & Surface Cleaner',
                    'name_ar' => 'منظف زجاج وسطوح',
                    'name_ku' => 'پاککاریی شیشە و سەطوح',
                    'small_description_en' => 'Streak-free cleaner for glass and surfaces',
                    'small_description_ar' => 'منظف خالي من الخطوط للزجاج والسطوح',
                    'small_description_ku' => 'پاککاریی بێ هێڵ بۆ شیشە و سەطوح',
                    'unit_price' => 2.80,
                    'shelf_price' => 3.20,
                    'old_price' => null,
                    'available_quantity' => 80,
                    'threshold' => 5,
                    'product_line_code' => 'CLN01',
                    'product_line_description' => 'Cleaning Solutions',
                    'family_code' => 'GLASS',
                    'family_description' => 'Glass & Surface',
                    'subcategories_id' => 2,
                    'brands_id' => 1,
                    'tax_id' => 1,
                    'hidden' => 0,
                    'automatic_hide' => 0,
                    'cancelled' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'sku' => 'P0003',
                    'barcode' => '1234567890123',
                    'extension' => null,
                    'name_en' => 'Sanita My Shield Adult Mask',
                    'name_ar' => 'قناع سانيتا ماي شيلد للكبار',
                    'name_ku' => 'ماسكی گەورەکانی سانیتا شیلد',
                    'small_description_en' => 'Protective mask for adults',
                    'small_description_ar' => 'قناع وقائي للكبار',
                    'small_description_ku' => 'ماسكی پاراستن بۆ گەورەکان',
                    'unit_price' => 5.00,
                    'shelf_price' => 5.50,
                    'old_price' => null,
                    'available_quantity' => 150,
                    'threshold' => 10,
                    'product_line_code' => 'PRT01',
                    'product_line_description' => 'Protection & Hygiene',
                    'family_code' => 'MASK',
                    'family_description' => 'Masks',
                    'subcategories_id' => 7,
                    'brands_id' => 2,
                    'tax_id' => 1,
                    'hidden' => 0,
                    'automatic_hide' => 0,
                    'cancelled' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'sku' => 'P0004',
                    'barcode' => '1234567890124',
                    'extension' => 'jpg',
                    'name_en' => 'Happies Baby Diapers Size 3',
                    'name_ar' => 'حفاضات هابييز مقاس 3',
                    'name_ku' => 'پانتەڵۆنی منداڵی هەپییز قەبارەی ٣',
                    'small_description_en' => 'Comfortable and absorbent diapers for babies',
                    'small_description_ar' => 'حفاضات مريحة وامتصاص عالية للأطفال',
                    'small_description_ku' => 'پانتەڵۆنەکانی منداڵ بۆ ئارامبوون و جەذب',
                    'unit_price' => 10.00,
                    'shelf_price' => 12.00,
                    'old_price' => 13.00,
                    'available_quantity' => 200,
                    'threshold' => 20,
                    'product_line_code' => 'BABY01',
                    'product_line_description' => 'Baby Hygiene',
                    'family_code' => 'DIAPER',
                    'family_description' => 'Diapers',
                    'subcategories_id' => 10,
                    'brands_id' => 3,
                    'tax_id' => 1,
                    'hidden' => 0,
                    'automatic_hide' => 0,
                    'cancelled' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'sku' => 'P0005',
                    'barcode' => null,
                    'extension' => 'jpg',
                    'name_en' => 'Dreams Facial Tissue Box',
                    'name_ar' => 'دريمز مناديل وجه',
                    'name_ku' => 'دریمز رەشووتی بەرەو چاو',
                    'small_description_en' => 'Soft and gentle facial tissues',
                    'small_description_ar' => 'مناديل وجه ناعمة ولطيفة',
                    'small_description_ku' => 'رەشووتە نرم و لەززە',
                    'unit_price' => 1.50,
                    'shelf_price' => 2.00,
                    'old_price' => null,
                    'available_quantity' => 300,
                    'threshold' => 15,
                    'product_line_code' => 'FAM01',
                    'product_line_description' => 'Family Hygiene',
                    'family_code' => 'TISSUE',
                    'family_description' => 'Facial Tissue',
                    'subcategories_id' => 5,
                    'brands_id' => 4,
                    'tax_id' => 1,
                    'hidden' => 0,
                    'automatic_hide' => 0,
                    'cancelled' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
                [
                    'sku' => 'P0006',
                    'barcode' => '1234567890125',
                    'extension' => null,
                    'name_en' => 'Private Adult Incontinence Pads',
                    'name_ar' => 'فوط سلس البول للبالغين',
                    'name_ku' => 'پەدی نەشیاوی گەورەکان',
                    'small_description_en' => 'Absorbent adult pads for incontinence',
                    'small_description_ar' => 'فوط ماصة لسلس البول للبالغين',
                    'small_description_ku' => 'پەدێکی جەذب بۆ نەشیاوی گەورەکان',
                    'unit_price' => 8.00,
                    'shelf_price' => 9.00,
                    'old_price' => null,
                    'available_quantity' => 120,
                    'threshold' => 10,
                    'product_line_code' => 'PARA01',
                    'product_line_description' => 'Adult Incontinence',
                    'family_code' => 'PAD',
                    'family_description' => 'Incontinence Pads',
                    'subcategories_id' => 3,
                    'brands_id' => 5,
                    'tax_id' => 1,
                    'hidden' => 0,
                    'automatic_hide' => 0,
                    'cancelled' => 0,
                    'created_at' => now(),
                    'updated_at' => now(),
                ],
            ]
        );
    }
}
