<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Str;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'extension' => 'jpg',
                'sku' => 'SSU001',
                'subcategories_id' => 9,
                'name_en' => 'Sanita Serv-U Maxi Roll 350m',
                'name_ar' => 'رول ماكسي 350 متر من سانيتا سيرف-يو',
                'name_ku' => 'سانیتا سرو-یو رول ماکسی 350 متر',
                'small_description_en' => '1-ply embossed white paper towel roll, 350 meters.',
                'small_description_ar' => 'لفة مناديل بيضاء من طبقة واحدة منقوشة بطول 350 متر.',
                'small_description_ku' => 'رۆلی تاکە لایەیی سپی بەبەرزی ٣٥٠ مەتر، دانەدار.',
                'unit_price' => 3.50,
                'shelf_price' => 4.00,
                'threshold' => 10,
                'product_line_code' => 'PT001',
                'product_line_description' => 'Paper Towels',
                'family_code' => 'FAM001',
                'family_description' => 'Home Care',
                'brands_id' => 1,
                'tax_id' => 1,
                'available_quantity' => 500,
                'hidden' => 0,
                'automatic_hide' => 0,
                'cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'extension' => 'jpg',
                'sku' => 'SSU002',
                'subcategories_id' => 8,
                'name_en' => 'Sanita Serv-U Floor Mopping Sanitizer 5L',
                'name_ar' => 'مطهر تنظيف الأرضيات 5 لتر من سانيتا سيرف-يو',
                'name_ku' => 'سانیتا سرو-یو مطهر کف‌شویی ٥ لیتری',
                'small_description_en' => '5-liter blue floor mopping sanitizer for effective cleaning.',
                'small_description_ar' => 'مطهر أزرق 5 لتر لتنظيف الأرضيات بفعالية.',
                'small_description_ku' => 'ماسیحی شۆردەری ٥ لیتری شین بۆ پاککردنەوەی ئەرض.',
                'unit_price' => 15.00,
                'shelf_price' => 17.00,
                'threshold' => 5,
                'product_line_code' => 'CL001',
                'product_line_description' => 'Cleaning Products',
                'family_code' => 'FAM002',
                'family_description' => 'Professional Hygiene',
                'brands_id' => 1,
                'tax_id' => 2,
                'available_quantity' => 200,
                'hidden' => 0,
                'automatic_hide' => 0,
                'cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'extension' => 'jpg',
                'sku' => 'SSU003',
                'subcategories_id' => 9,
                'name_en' => 'Sanita Serv-U Disposable Vinyl Gloves - Medium',
                'name_ar' => 'قفازات فينيل ذات استخدام واحد - وسط',
                'name_ku' => 'دەستی وینیلی یەکجار بەکاربەر - ناوەند',
                'small_description_en' => 'Box of 100 medium-sized blue vinyl disposable gloves.',
                'small_description_ar' => 'علبة تحتوي على 100 قفاز فينيل أزرق متوسط الحجم للاستخدام الواحد.',
                'small_description_ku' => 'بۆکسێک ١٠٠ دەستکش وینیلی شین ناوەند، بۆ بەکارهێنانی یەکجار.',
                'unit_price' => 8.00,
                'shelf_price' => 9.50,
                'threshold' => 20,
                'product_line_code' => 'GL001',
                'product_line_description' => 'Gloves',
                'family_code' => 'FAM003',
                'family_description' => 'Personal Protection',
                'brands_id' => 1,
                'tax_id' => 1,
                'available_quantity' => 300,
                'hidden' => 0,
                'automatic_hide' => 0,
                'cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'extension' => 'jpg',
                'sku' => 'SSU004',
                'subcategories_id' => 8,
                'name_en' => 'Sanita Serv-U 150 Sheets Brown Interfold Towel Tissue',
                'name_ar' => 'منديل مناديل بنية مكونة من 150 ورقة مناديل',
                'name_ku' => '150 برگەی تیشەوی قەوەیی سانیتا سرو-یو',
                'small_description_en' => '150-sheet pack of 2-ply brown interfold towel tissues made from recycled materials.',
                'small_description_ar' => 'عبوة من 150 منديل بني من طبقتين مصنوعة من مواد معاد تدويرها.',
                'small_description_ku' => 'پاکەتێک ١٥٠ برگی دوو لایەیی قەوەیی لە مادەی بەرگەکراوەوە.',
                'unit_price' => 2.00,
                'shelf_price' => 2.50,
                'threshold' => 15,
                'product_line_code' => 'NT001',
                'product_line_description' => 'Napkins & Tissues',
                'family_code' => 'FAM004',
                'family_description' => 'Home Essentials',
                'brands_id' => 1,
                'tax_id' => 1,
                'available_quantity' => 400,
                'hidden' => 0,
                'automatic_hide' => 0,
                'cancelled' => 0,
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}
