<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ProductsSeeder extends Seeder
{
    public function run(): void
    {
        DB::table('products')->insert([
            [
                'sku' => 'SAN-ALF-30',
                'barcode' => '6281234567890',
                'extension' => 'roll',
                'name_en' => 'Sanita Aluminum Foil 30m',
                'name_ar' => 'رقائق ألومنيوم سانيتا 30 متر',
                'name_ku' => 'فوی ئه‌لومینیۆمی سانیتا ٣٠ متر',
                'small_description_en' => 'Durable aluminum foil for household use',
                'small_description_ar' => 'رقائق ألومنيوم متينة للاستخدام المنزلي',
                'small_description_ku' => 'فوی ئه‌لومینیۆمی بەردەوام بۆ بەکارهێنانی خانوو',
                'ea_ca' => 12,
                'ea_pl' => 240,
                'subcategories_id' => 2,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-ALF-50',
                'barcode' => '6281234567891',
                'extension' => 'roll',
                'name_en' => 'Sanita Aluminum Foil 50m',
                'name_ar' => 'رقائق ألومنيوم سانيتا 50 متر',
                'name_ku' => 'فوی ئه‌لومینیۆمی سانیتا ٥٠ متر',
                'small_description_en' => 'Extra-long aluminum foil for kitchen needs',
                'small_description_ar' => 'رقائق ألومنيوم طويلة للاستخدام في المطبخ',
                'small_description_ku' => 'فوی ئه‌لومینیۆمی درێژ بۆ پێویستی خواردن',
                'ea_ca' => 12,
                'ea_pl' => 240,
                'subcategories_id' => 2,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-CF-20',
                'barcode' => '6281234567892',
                'extension' => 'roll',
                'name_en' => 'Sanita Cling Film 20m',
                'name_ar' => 'فيلم تغليف سانيتا 20 متر',
                'name_ku' => 'فیلم پلاستیکی سانیتا ٢٠ متر',
                'small_description_en' => 'Transparent cling film for food preservation',
                'small_description_ar' => 'فيلم تغليف شفاف لحفظ الطعام',
                'small_description_ku' => 'فیلمی پلاستیکی روون بۆ پاراستنی خواردن',
                'ea_ca' => 24,
                'ea_pl' => 480,
                'subcategories_id' => 2,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-CF-30',
                'barcode' => '6281234567893',
                'extension' => 'roll',
                'name_en' => 'Sanita Cling Film 30m',
                'name_ar' => 'فيلم تغليف سانيتا 30 متر',
                'name_ku' => 'فیلم پلاستیکی سانیتا ٣٠ متر',
                'small_description_en' => 'Strong cling film, suitable for all foods',
                'small_description_ar' => 'فيلم تغليف قوي، مناسب لجميع أنواع الطعام',
                'small_description_ku' => 'فیلمی پلاستیکی بەهێز بۆ هەموو جۆری خواردن',
                'ea_ca' => 24,
                'ea_pl' => 480,
                'subcategories_id' => 2,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-GB-30L',
                'barcode' => '6281234567894',
                'extension' => 'bag',
                'name_en' => 'Sanita Garbage Bags 30L',
                'name_ar' => 'أكياس نفايات سانيتا 30 لتر',
                'name_ku' => 'کۆرەکانی زەبڵی سانیتا ٣٠ لیتر',
                'small_description_en' => 'Heavy duty garbage bags for household trash',
                'small_description_ar' => 'أكياس نفايات قوية للاستخدام المنزلي',
                'small_description_ku' => 'کۆرەکانی زەبڵی هەڵگرتنی خانوو بەردەوام',
                'ea_ca' => 10,
                'ea_pl' => 200,
                'subcategories_id' => 11,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-GB-50L',
                'barcode' => '6281234567895',
                'extension' => 'bag',
                'name_en' => 'Sanita Garbage Bags 50L',
                'name_ar' => 'أكياس نفايات سانيتا 50 لتر',
                'name_ku' => 'کۆرەکانی زەبڵی سانیتا ٥٠ لیتر',
                'small_description_en' => 'Large size garbage bags for industrial use',
                'small_description_ar' => 'أكياس نفايات كبيرة للاستخدام الصناعي',
                'small_description_ku' => 'کۆرەکانی زەبڵی گەورە بۆ بەکارهێنانی صنعتی',
                'ea_ca' => 10,
                'ea_pl' => 200,
                'subcategories_id' => 11,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-TP-200',
                'barcode' => '6281234567896',
                'extension' => 'pack',
                'name_en' => 'Sanita Tissue Paper 200pcs',
                'name_ar' => 'ورق مناديل سانيتا 200 قطعة',
                'name_ku' => 'کاغەزی مندیلەکانی سانیتا ٢٠٠ دانە',
                'small_description_en' => 'Soft tissue paper for everyday use',
                'small_description_ar' => 'ورق منديل ناعم للاستخدام اليومي',
                'small_description_ku' => 'کاغەزی مندیل نرمی بۆ بەکارهێنانی ڕۆژانە',
                'ea_ca' => 20,
                'ea_pl' => 400,
                'subcategories_id' => 9,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-TP-300',
                'barcode' => '6281234567897',
                'extension' => 'pack',
                'name_en' => 'Sanita Tissue Paper 300pcs',
                'name_ar' => 'ورق مناديل سانيتا 300 قطعة',
                'name_ku' => 'کاغەزی مندیلەکانی سانیتا ٣٠٠ دانە',
                'small_description_en' => 'Extra soft tissue paper for sensitive skin',
                'small_description_ar' => 'ورق منديل ناعم جداً للبشرة الحساسة',
                'small_description_ku' => 'کاغەزی مندیل زۆر نرمی بۆ پوستە هەستیارەکان',
                'ea_ca' => 20,
                'ea_pl' => 400,
                'subcategories_id' => 9,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-WW-80',
                'barcode' => '6281234567898',
                'extension' => 'pack',
                'name_en' => 'Sanita Wet Wipes 80pcs',
                'name_ar' => 'مناديل مبللة سانيتا 80 قطعة',
                'name_ku' => 'مندیلە خێراکانی سانیتا ٨٠ دانە',
                'small_description_en' => 'Moist wipes with gentle formula',
                'small_description_ar' => 'مناديل مبللة بتركيبة لطيفة',
                'small_description_ku' => 'مندیلە خێراکانی بە فۆرمولەیەکی نرم',
                'ea_ca' => 15,
                'ea_pl' => 300,
                'subcategories_id' => 9,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-WW-120',
                'barcode' => '6281234567899',
                'extension' => 'pack',
                'name_en' => 'Sanita Wet Wipes 120pcs',
                'name_ar' => 'مناديل مبللة سانيتا 120 قطعة',
                'name_ku' => 'مندیلە خێراکانی سانیتا ١٢٠ دانە',
                'small_description_en' => 'Large pack of wet wipes for family use',
                'small_description_ar' => 'عبوة كبيرة من المناديل المبللة للاستخدام العائلي',
                'small_description_ku' => 'پاکەی گەورەی مندیلە خێراکانی بۆ بەکارهێنانی خێزان',
                'ea_ca' => 15,
                'ea_pl' => 300,
                'subcategories_id' => 9,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-DP-M',
                'barcode' => '6281234567800',
                'extension' => 'pack',
                'name_en' => 'Sanita Baby Diapers Size M',
                'name_ar' => 'حفاضات أطفال سانيتا مقاس M',
                'name_ku' => 'پۆشەی منداڵانی سانیتا قەبارە M',
                'small_description_en' => 'Comfortable diapers for babies',
                'small_description_ar' => 'حفاضات مريحة للأطفال',
                'small_description_ku' => 'پۆشەی خۆش بۆ منداڵان',
                'ea_ca' => 8,
                'ea_pl' => 160,
                'subcategories_id' => 3,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-DP-L',
                'barcode' => '6281234567801',
                'extension' => 'pack',
                'name_en' => 'Sanita Baby Diapers Size L',
                'name_ar' => 'حفاضات أطفال سانيتا مقاس L',
                'name_ku' => 'پۆشەی منداڵانی سانیتا قەبارە L',
                'small_description_en' => 'Soft and absorbent diapers for babies',
                'small_description_ar' => 'حفاضات ناعمة وامتصاصية للأطفال',
                'small_description_ku' => 'پۆشەی نرمی و هەڵگیر بۆ منداڵان',
                'ea_ca' => 8,
                'ea_pl' => 160,
                'subcategories_id' => 3,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-SP-XL',
                'barcode' => '6281234567802',
                'extension' => 'pack',
                'name_en' => 'Sanita Sanitary Pads XL',
                'name_ar' => 'فوط صحية سانيتا مقاس XL',
                'name_ku' => 'پادەکانی سەنتاری سانیتا قەبارە XL',
                'small_description_en' => 'Extra-large sanitary pads for heavy flow',
                'small_description_ar' => 'فوط صحية كبيرة للتدفق الغزير',
                'small_description_ku' => 'پادە سەنتاری گەورە بۆ هەڵکێشانی زۆر',
                'ea_ca' => 10,
                'ea_pl' => 200,
                'subcategories_id' => 5,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-SP-N',
                'barcode' => '6281234567803',
                'extension' => 'pack',
                'name_en' => 'Sanita Sanitary Pads Normal',
                'name_ar' => 'فوط صحية سانيتا عادية',
                'name_ku' => 'پادەکانی سەنتاری سانیتا بە شێوەی عادی',
                'small_description_en' => 'Regular sanitary pads for everyday comfort',
                'small_description_ar' => 'فوط صحية عادية للراحة اليومية',
                'small_description_ku' => 'پادە سەنتارییەکانی عادی بۆ ئاسایش ڕۆژانە',
                'ea_ca' => 10,
                'ea_pl' => 200,
                'subcategories_id' => 5,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-CN-50',
                'barcode' => '6281234567804',
                'extension' => 'pack',
                'name_en' => 'Sanita Cotton Balls 50pcs',
                'name_ar' => 'كرات قطن سانيتا 50 قطعة',
                'name_ku' => 'تووشکەکانی کۆتن سانیتا ٥٠ دانە',
                'small_description_en' => 'Pure cotton balls for hygienic use',
                'small_description_ar' => 'كرات قطن نقي للاستخدام الصحي',
                'small_description_ku' => 'تووشکەکانی کۆتن پاک بۆ بەکارهێنانی تەندروستی',
                'ea_ca' => 30,
                'ea_pl' => 600,
                'subcategories_id' => 9,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-CS-200',
                'barcode' => '6281234567805',
                'extension' => 'pack',
                'name_en' => 'Sanita Cotton Sticks 200pcs',
                'name_ar' => 'عيدان قطن سانيتا 200 قطعة',
                'name_ku' => 'ستیکی کۆتن سانیتا ٢٠٠ دانە',
                'small_description_en' => 'Cotton swabs for personal care',
                'small_description_ar' => 'عيدان قطن للعناية الشخصية',
                'small_description_ku' => 'ستیکی کۆتن بۆ چاودێری کەسی',
                'ea_ca' => 30,
                'ea_pl' => 600,
                'subcategories_id' => 9,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-LS-500',
                'barcode' => '6281234567806',
                'extension' => 'bottle',
                'name_en' => 'Sanita Liquid Soap 500ml',
                'name_ar' => 'صابون سائل سانيتا 500 مل',
                'name_ku' => 'صابونی مای سانیتا ٥٠٠ میل',
                'small_description_en' => 'Antibacterial liquid soap for hand hygiene',
                'small_description_ar' => 'صابون سائل مضاد للبكتيريا لنظافة اليدين',
                'small_description_ku' => 'صابونی مای بەرەنگاربوو بۆ پاکی دەست',
                'ea_ca' => 12,
                'ea_pl' => 240,
                'subcategories_id' => 1,
                'brands_id' => 6,
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'sku' => 'SAN-HS-250',
                'barcode' => '6281234567807',
                'extension' => 'bottle',
                'name_en' => 'Sanita Hand Sanitizer 250ml',
                'name_ar' => 'معقم يد سانيتا 250 مل',
                'name_ku' => 'پاککەرەوەی دەست سانیتا ٢٥٠ میل',
                'small_description_en' => 'Quick-dry hand sanitizer with moisturizing agents',
                'small_description_ar' => 'معقم يد يجف بسرعة مع عوامل ترطيب',
                'small_description_ku' => 'پاککەرەوەی دەست بە خێرایی و ئاژەڵەکانی لێخۆشکەر',
                'ea_ca' => 24,
                'ea_pl' => 480,
                'subcategories_id' => 1,
                'brands_id' => 9,
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
