<input type="hidden" id="modalProductUOM" name="UOM">
<input type="hidden" id="modalProductId" name="product_id">
<input type="hidden" id="modalProductShelfPrice" name="shelf_price">
<input type="hidden" id="modalProductUnitPrice" name="unit_price">
<input type="hidden" id="modalProductOldPrice" name="old_price">
<input type="hidden" id="modalProductType" name="type">
<input type="hidden" id="modalProductName" name="name">
<input type="hidden" id="modalProductDescription" name="description">
<input type="hidden" id="modalProductEaCa" name="ea-ca">
<input type="hidden" id="modalProductEaPl" name="ea-pl">
<input type="hidden" id="modalProductEa" name="ea">
<input type="hidden" id="modalProductCa" name="ca">
<input type="hidden" id="modalProductPl" name="pl">
<input type="hidden" id="modalProductMinQuantity" name="min_quantity">
<input type="hidden" id="modalProductMaxQuantity" name="max_quantity">